version: '3.6'
services:
  app:
    image: registry.local:5000/training/user-management
    container_name: lilium_userm_app
    restart: always
    environment:
      API_URL: 'http://localhost:3000'
      DB_HOST: 'lilium_userm_db.local'
      DB_NAME: 'lilium'
      DB_USERNAME: 'lilium'
      DB_PASSWORD: 'lilium'
    ports:
      - '3000:3000'
    shm_size: '256m'
  db:
    image: postgres
    container_name: lilium_userm_db
    restart: always
    environment:
      POSTGRES_USER: 'lilium'
      POSTGRES_PASSWORD: 'lilium'
      POSTGRES_DB: 'lilium'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10     
  registry:
    image: registry:2.7
    container_name: registry
    restart: always
    hostname: 'registry.local'
    ports:
      - '5000:5000'       