apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
  namespace: default
data:
  NEXT_PUBLIC_API_URL: https://appusermanagementararog.loclx.io/
  DB_HOST: todo-postgresql.default.svc.cluster.local
  DB_NAME: lilium
  DB_USERNAME: postgres
